#####################################################################################################################
# Documentation: https://bitbucket.org/zepben/how-tos/src/master/bitbucket_pipelines/release-management.md
# Custom Images used: https://bitbucket.org/zepben/vm-container-images/
#####################################################################################################################
image: python:3.7-slim

options:
  max-time: 30

definitions:
  zep-basic-image: &zep-basic-image
    image: zepben/pipeline-basic:2.0.0

  steps:
    - step: &run-tests-step
        name: Test
        caches:
          - pip
        script:
          - python -m pip install pytest
          - cd test
          - pytest
    - step: &release-step
        name: Package and Upload artifact
        caches:
          - pip
        script:
          - python -m pip install twine
          - python setup.py sdist
          - twine upload --repository-url "$ZEPBEN_PYPI_REPO" -u "$ZEPBEN_PYPI_USERNAME" -p "$ZEPBEN_PYPI_PASSWORD" dist/*
    
    - step: &update-snapshot-version
        <<: *zep-basic-image
        name: Update project version to next snapshot
        script:
          - py-update-version --snapshot setup.py

pipelines:
  branches:
    master: 
      - step: *run-tests-step
      - step: *release-step
      - step: *update-snapshot-version
    LTS/*:
      - step: *run-tests-step
      - step: *release-step
      - step: *update-snapshot-version
  pull-requests:
    '**': 
      - step: *run-tests-step
  tags:
    '*.*.*':
      - step: *release-step
          
  custom:
    create-release:
      - step:
          name: Create release
          <<: *zep-basic-image
          script:
            - release-checks
            - py-finalize-version setup.py
            - py-update-version --release setup.py
            - rebase

    create-LTS-branch:
      - step:
          <<: *zep-basic-image
          name: Create LTS branch
          script:
            - create-branch --lts
            - export BITBUCKET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            - py-update-version setup.py

    create-hotfix-branch:
      - step:
          <<: *zep-basic-image
          name: Create Hotfix branch
          script:
            - create-branch --hotfix
            - export BITBUCKET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            - py-update-version setup.py